# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Snapshots of my thoughts
email: srinivas.muddana@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000/" # the base hostname & protocol for your site
github.url : "http://muddana.github.io/"
twitter_username: MUDDANA
github_username:  muddana
resume_link: https://drive.google.com/file/d/0BzJFlLjTbohPd3pxdHU4bG5EM3c/view?usp=sharing 

# Build settings
markdown: kramdown

#other settings

